version: '3.7'
services:
  minio:
    container_name: minio
    image: minio/minio  
    volumes:
      - ./receive:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      - backend
    command: server /data
  python-service:
    container_name: controller
    image: kushagramttl/samplecontroller
    volumes: 
      - ./send:/usr/src/code/data
    depends_on:
      - minio
    networks:
      - backend
networks:
  backend:
    driver: bridge