version: '3.7'
services:
  minio:
    container_name: minio
    build:
      context: ./minio
      dockerfile: Dockerfile
    volumes:
      - ./receive:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    networks:
      - backend
    command: server /data
  python-service:
    build:
      context: ./scripts
      dockerfile: Dockerfile
    volumes:
      - ./send:/data
    depends_on:
      - minio
    networks:
      - backend
volumes: 
  data-1:
networks:
  backend:
    driver: bridge