version: '3.7'
services:
  minio:
    container_name: dtnib_minio
    image: minio/minio  
    volumes:
      - ./receive:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data
  rclone:
    container_name: rclone
    image: kushagramttl/rclone
    ports: 
      - "5572:5572"
    networks:
      - backend
    volumes: 
      - ./send:/root/data
  controller:
    container_name: controller
    image: kushagramttl/samplecontroller
    networks:
      - backend
    depends_on:
      - minio
      - rclone
networks:
  backend:
    driver: bridge 
  
    